# Generated by Django 3.2.4 on 2021-06-19 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aqsa', '0002_course_popular'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='video',
            field=models.FileField(blank=True, upload_to='videos/'),
        ),
    ]
