# Generated by Django 3.2.4 on 2021-06-21 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aqsa', '0005_delete_studentreview'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_logo', models.ImageField(blank=True, upload_to='logo/')),
                ('footer_logo', models.ImageField(blank=True, upload_to='logo/')),
                ('short_description', models.TextField()),
                ('opening_hours', models.CharField(blank=True, max_length=250)),
                ('helpline', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
