# Generated by Django 3.2.4 on 2021-06-21 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aqsa', '0006_setting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='opening_hours',
        ),
        migrations.AddField(
            model_name='setting',
            name='address',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='setting',
            name='official_mail',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
